<?php
/**
 * @license GPL-2.0-only
 *
 * Modified by __root__ on 29-March-2026 using {@see https://github.com/BrianHenryIE/strauss}.
 */

namespace FluentPdf\Vendor\Mpdf\Tag;

class Pre extends BlockTag
{

	public function open($attr, &$ahtml, &$ihtml)
	{
		$this->mpdf->ispre = true; // ADDED - Prevents left trim of textbuffer in printbuffer()
		parent::open($attr, $ahtml, $ihtml); // TODO: Change the autogenerated stub
	}
}
